all: baryon uvlf xi smf sfr mgross coldgas hotgas

baryon:
	python baryon_frac.py 75
	python baryon_frac.py 49
	python baryon_frac.py 34
uvlf:
	python plot_uv.py
xi:
	python plot_xi.py
smf:
	python plot_smf.py
sfr:
	python plot_sfr2.py
mgross:
	python mgross_vs_m200c.py
hotgas:
	python plot_hotgas.py
coldgas:
	python plot_coldgas.py
xfrachist:
	python plot_xfrachist.py
